### ISSUE TITLE
Instructions don't tell what to do with original Steam.dll

### ISSUE THREAD

**Issue by nsrosenqvist** [0x0ade/DuckGame-Linux#1]
When you've gotten the game files from Steam there is already a Steam.dll in the game folder and the instructions don't say whether to overwrite the original dll or not. (I simply renamed the old one to Steam.dll.old and tested if it worked)

**Comment by 0x0ade** [comment]
Good point, I'll add a note telling the user to overwrite all files with the .zipped ones. You don't need the original Steam.dll on Linux anyway. Thanks!
