### ISSUE TITLE
mod.sh missing in package

### ISSUE THREAD

**Issue by kblack373** [0x0ade/DuckGame-Linux#8]
I followed all of the instructions in the ReadMe but I think I'm either missing something or the package is broken. When I run `chmod a+x ./mod.sh; ./mod.sh`, I get the error that mod.sh does not exist. Running `mono DuckGame.exe` therefore does not work.

As a sidenote, I'm just a little confused about the organization of the .ZIP as the instructions say to extract into the DuckGame directory, but the necessary files are dispersed among different folders. I would just like a little clarification and a point in the right direction. I love this port and had it a few working on a different machine a few months ago, but now I can't get it.

**Comment by 0x0ade** [comment]
Please download [`DuckGame-Linux-Complete.zip` from the releases tab.](https://github.com/0x0ade/DuckGame-Linux/releases) `mod.sh` exists in that package, and all files are at the top level.
